name: bgug
description: Break Guns Using Blocks!

dependencies:
  flutter:
    sdk: flutter
  flame:
    path: ../flame
  shared_preferences: 0.4.1
  firebase_admob: 0.5.4
  google_sign_in: 3.0.3
  firebase_auth: 0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/images/skins/gold.png # TODO other skins
   - assets/images/hud_bg.png
   - assets/images/btns/coin.png
   - assets/images/btns/player_1.png
   - assets/images/btns/player_2.png
   - assets/images/player_1.png
   - assets/images/player_2.png
   - assets/images/base_bottom.png
   - assets/images/base_top.png
   - assets/images/block.png
   - assets/images/obstacle.png
   - assets/images/shooter.png
   - assets/images/bullet.png
   - assets/images/gem.png
   - assets/images/coin.png
   - assets/images/coin_button.png
   - assets/images/bg.png
   - assets/images/button.png
   - assets/images/endgame_bg.png
   - assets/images/endgame_buttons.png
   - assets/images/tutorial.png
   - assets/images/splash_screen.png
   - assets/images/store/skins_panel.png
   - assets/images/store/store_button.png
   - assets/images/store/store-ui.png
   - assets/images/store/times_2_panel.png
   - assets/images/store/x2coins-certificate.png
   - assets/audio/death.wav
   - assets/audio/gem_collect.wav
   - assets/audio/jump.wav
   - assets/audio/laser_load.wav
   - assets/audio/laser_shoot.wav
   - assets/audio/music.wav
  fonts:
    - family: 5x5
      fonts:
        - asset: assets/fonts/5x5_pixel.ttf
    - family: Blox2
      fonts:
        - asset: assets/fonts/blox2.ttf
    - family: Squared Display
      fonts:
        - asset: assets/fonts/squared_display.ttf
