name: bgug
description: Break Guns Using Blocks!

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 0.3.1
  firebase_admob: 0.2.3
  flame:
    path: ../../flame

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/images/player.png
   - assets/images/base.png
   - assets/images/block.png
   - assets/images/obstacle.png
   - assets/images/shooter.png
   - assets/images/bullet.png
   - assets/images/gem.png
   - assets/images/bg.png
   - assets/images/button.png
   - assets/audio/death.wav
   - assets/audio/gem_collect.wav
   - assets/audio/jump.wav
   - assets/audio/laser_load.wav
   - assets/audio/laser_shoot.wav
   - assets/audio/music.wav
  fonts:
    - family: Blox2
      fonts:
        - asset: assets/fonts/blox2.ttf
    - family: Squared Display
      fonts:
        - asset: assets/fonts/squared_display.ttf