name: bgug
description: Break Guns Using Blocks!

dependencies:
  flutter:
    sdk: flutter
  flame:
    path: ../../flame

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/images/player.png
   - assets/images/base.png
   - assets/images/block.png
   - assets/images/obstacle.png
   - assets/images/shooter.png
   - assets/images/bullet.png
   - assets/images/bg.png
  fonts:
    - family: Blox2
      fonts:
        - asset: assets/fonts/blox2.ttf
    - family: Squared Display
      fonts:
        - asset: assets/fonts/squared_display.ttf