name: bgug
description: Break Guns Using Blocks!

dependencies:
  flutter:
    sdk: flutter
  flame: 0.9.5
  shared_preferences: 0.4.1
  firebase_admob: 0.5.4
  google_sign_in: 3.0.3
  firebase_auth: 0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/images/btns/coin.png
   - assets/images/btns/player_1.png
   - assets/images/btns/player_2.png
   - assets/images/player_1.png
   - assets/images/player_2.png
   - assets/images/base.png
   - assets/images/block.png
   - assets/images/obstacle.png
   - assets/images/shooter.png
   - assets/images/bullet.png
   - assets/images/gem.png
   - assets/images/coin.png
   - assets/images/coin_button.png
   - assets/images/bg.png
   - assets/images/button.png
   - assets/audio/death.wav
   - assets/audio/gem_collect.wav
   - assets/audio/jump.wav
   - assets/audio/laser_load.wav
   - assets/audio/laser_shoot.wav
   - assets/audio/music.wav
  fonts:
    - family: Blox2
      fonts:
        - asset: assets/fonts/blox2.ttf
    - family: Squared Display
      fonts:
        - asset: assets/fonts/squared_display.ttf
